#!/usr/bin/env php
<?php

/**
 * Initializes the core application.
 */
$app = require './bootstrap.php';

/**
 * Executes the provided command using
 * default input and output implementation.
 *
 * @var \Framework\Command\Application
 */
$commander = $app->get('console');
$commander->run();
